version = 2
name = "Untitled Project"
description = "No Description"
secretKey = "exp626"
adminPassword = "danishpowers"
requireLogin = false
hideDeleteNodeButton = false
allowLoggedInUserToImport = false
nodeSizeDefault = 5
nodeSizeMax = 50
edgeSizeDefault = 1
edgeSizeMax = 25
filterFade = "Fade"
filterFadeHelp = "Show matches, Fade others"
filterReduce = "Reduce"
filterReduceHelp = "Show matches, Reduce (remove) others & recalculate sizes"
filterFocus = "Focus"
filterFocusHelp = "Show only nodes connected to the selected node within range"
duplicateWarning = "NOTE: At least one other node has the same name. Use search or the node table to check the others."
nodeIsLockedMessage = "This node is currently being edited by someone else, please try again later."
edgeIsLockedMessage = "This edge is currently being edited by someone else, please try again later."
templateIsLockedMessage = "The template is currently being edited, please try again later."
importIsLockedMessage = "Data is currently being imported, please try again later."
nodeDefaultTransparency = 1
edgeDefaultTransparency = 0.7
searchColor = "#008800"
sourceColor = "#FFa500"

[citation]
text = "No citation set"
hidden = false

[[commentTypes]]
slug = "cmt"
label = "Comment"

  [[commentTypes.prompts]]
  format = "text"
  prompt = "Comment"
  help = "Use this for any general comment."
  feedback = ""

[[commentTypes]]
slug = "tellmemore"
label = "Evidence Critique or Suggestion"

  [[commentTypes.prompts]]
  format = "text"
  prompt = "Tell me more"
  help = "Can you tell me more about ... "
  feedback = ""

[nodeDefs.id]
type = "number"
displayLabel = "Id"
exportLabel = "ID"
help = "System-generated unique id number"
includeInGraphTooltip = true
isProvenance = false
hidden = false

[nodeDefs.label]
type = "string"
displayLabel = "Label"
exportLabel = "Label"
help = "Display name of the node"
includeInGraphTooltip = true
isProvenance = false
hidden = false

[nodeDefs.type]
type = "select"
displayLabel = "Type"
exportLabel = "NodeType"
help = "Select a category"
includeInGraphTooltip = true
isProvenance = false
hidden = false

  [[nodeDefs.type.options]]
  color = "#eeeeee"
  label = ""

[nodeDefs.notes]
type = "string"
displayLabel = "Notes"
exportLabel = "Notes"
help = "General purpose notes text field"
includeInGraphTooltip = true
isProvenance = false
hidden = false

[nodeDefs.info]
type = "number"
displayLabel = "Number"
exportLabel = "Info"
help = "Some number comparison"
includeInGraphTooltip = true
isProvenance = false
hidden = false

[nodeDefs.infoSource]
type = "infoOrigin"
displayLabel = "Info Source"
exportLabel = "InfoSource"
help = "Who created this?  (aka Source)"
includeInGraphTooltip = true
isProvenance = true
hidden = false

[nodeDefs.degrees]
type = "number"
displayLabel = "Degrees"
exportLabel = "Degrees"
help = "Number of edges connected to this node"
includeInGraphTooltip = true
isProvenance = false
hidden = false

[nodeDefs.created]
type = "timestamp"
displayLabel = "Created"
exportLabel = "Created"
help = "Date and time node was created"
includeInGraphTooltip = true
hidden = false

[nodeDefs.createdBy]
type = "string"
displayLabel = "Created By"
help = "Author who created the node"
exportLabel = "Created By"
includeInGraphTooltip = true
hidden = false

[nodeDefs.updated]
type = "timestamp"
displayLabel = "Updated"
exportLabel = "Updated"
help = "Date and time node was last modified"
includeInGraphTooltip = true
hidden = false

[nodeDefs.updatedBy]
type = "string"
displayLabel = "Updated By"
exportLabel = "Updated By"
help = "Author who updated the node"
includeInGraphTooltip = true
hidden = false

[nodeDefs.revision]
displayLabel = "Revision"
exportLabel = "Revision"
help = "Number of times this node has been revised"
includeInGraphTooltip = true
hidden = true

[edgeDefs.id]
type = "number"
displayLabel = "Id"
exportLabel = "ID"
help = "System-generated unique id number"
isProvenance = false
hidden = false

[edgeDefs.source]
type = "number"
displayLabel = "Source"
exportLabel = "Source"
help = "Edge source node"
isProvenance = false
hidden = false

[edgeDefs.target]
type = "number"
displayLabel = "Target"
exportLabel = "Target"
help = "Edge target node"
hidden = false

[edgeDefs.type]
type = "select"
displayLabel = "Type"
exportLabel = "EdgeType"
help = "Type of edge connection"
isProvenance = false
hidden = false

  [[edgeDefs.type.options]]
  color = "#eeeeee"
  label = ""

[edgeDefs.notes]
type = "string"
displayLabel = "Notes"
exportLabel = "Notes"
help = "Significance of the connection"
isProvenance = false
hidden = false

[edgeDefs.weight]
type = "weight"
defaultValue = 1
displayLabel = "Weight"
exportLabel = "Weight"
help = "Weight of edge"
includeInGraphTooltip = true
isRequired = true
isProvenance = false
hidden = false

[edgeDefs.infoOrigin]
type = "string"
displayLabel = "Info Origin"
exportLabel = "InfoOrigin"
help = "Who created this?  (aka Source)"
includeInGraphTooltip = true
isProvenance = true
hidden = false

[edgeDefs.citation]
type = "string"
displayLabel = "Citation"
exportLabel = "Citation"
help = 'Source Book.Chapter (e.g. "Part 2 06.03")'
isProvenance = false
hidden = false

[edgeDefs.category]
type = "string"
displayLabel = "Category"
exportLabel = "Category"
help = "Category (deprecated)"
isProvenance = false
hidden = true

[edgeDefs.created]
type = "timestamp"
displayLabel = "Created"
exportLabel = "Created"
includeInGraphTooltip = true
help = "Date and time edge was created"
hidden = false

[edgeDefs.createdBy]
type = "string"
displayLabel = "Created By"
exportLabel = "Created By"
includeInGraphTooltip = true
help = "Author who created the edge"
hidden = false

[edgeDefs.updated]
type = "timestamp"
displayLabel = "Updated"
exportLabel = "Updated"
includeInGraphTooltip = true
help = "Date and time edge was last modified"
hidden = false

[edgeDefs.updatedBy]
type = "string"
displayLabel = "Updated By"
exportLabel = "Updated By"
includeInGraphTooltip = true
help = "Author who updated the nodedgee"
hidden = false

[edgeDefs.revision]
displayLabel = "Revision"
exportLabel = "Revision"
includeInGraphTooltip = true
help = "Number of times this edge has been revised"
hidden = true
