# metadata
_schemaVersion: '2.0'
_schemaLayer: PropertyDefs

prompts:
  # filter tab panels
  filterFade:
    type: string
    default: 'Fade'
  filterFadeHelp:
    type: string
    default: 'Show matches, Fade others'
  filterReduce:
    type: string
    default: 'Reduce'
  filterReduceHelp:
    type: string
    default: 'Show matches, Reduce (remove) others & recalculate sizes'
  filterFocus:
    type: string
    default: 'Focus'
  filterFocusHelp:
    type: string
    default: 'Show only nodes connected to the selected node within range'

# Node Defaults for GraphView
nodeSettings:
  nodeSizeDefault:
    type: number
    default: 5
  nodeSizeMax:
    type: number
    default: 50
  nodeDefaultTransparency:
    type: number
    default: 1

# EdgeDefaults for GraphView
edgeSettings:
  edgeSizeDefault:
    type: number
    default: 1
  edgeSizeMax:
    type: number
    default: 25
  edgeDefaultTransparency:
    type: number
    default: 0.7

# Color Defaults for GraphView
colorSettings:
  searchColor:
    type: number
    default: '#008800' # color used to hilight a search result
  sourceColor:
    type: number
    default: '#FFa500' # color used to hilight a source
